title: MY TITLE
author: wudan
email: your-email@domain.com
Theme: minima
description: > # this means to ignore newlines until "baseurl:"
  HAAAAAAAAAAAAAAAAAAAAAAAAAA.

# social links
twitter_username: NOTWITTER
github_username:  WUDANONCE

show_excerpts: true # set to false to remove excerpts on the homepage
