title: OBLIVION
author: wudan
email: wudanonce@163.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  haaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

# social links
twitter_username: notwitter
github_username:  wudanonce

show_excerpts: true # set to false to remove excerpts on the homepage
